{{- if and (or (not (default false .Values.deploymentDisable)) .Values.job.enabled .Values.cronjob.enabled) (default true .Values.serviceAccount.create) }}
{{- $saAnnotations := dict }}
{{- with .Values.serviceAccount.annotations }}
  {{- $saAnnotations = mergeOverwrite $saAnnotations . }}
{{- end }}
{{- if .Values.job.enabled }}
  {{- with .Values.job.serviceAccountAnnotations }}
    {{- $saAnnotations = mergeOverwrite $saAnnotations . }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- with $saAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
