{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
{{- end }}
