{{- if and .Values.service.enabled (not (default false .Values.deploymentDisable)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- toYaml .Values.service.ports | nindent 4 }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ default .Values.service.name .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      {{- with .Values.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
      name: {{ .Values.service.name }}
    {{- end }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
{{- end }}
