apiVersion: v2
name: application
description: Universal Helm chart for deploying applications to Kubernetes
keywords:
  - universal-helm-chart
  - reusable-helm-chart
  - generic-helm-chart
  - application-helm-chart
  - kubernetes
  - helm
  - gitops
  - argocd
  - gateway-api

type: application

version: 0.3.4

appVersion: "0.1.6"

maintainers:
  - name: Vyacheslav Lochashvili
    email: v.lochashvili@protonmail.com
